// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FormfocusController from "./formfocus_controller"
application.register("formfocus", FormfocusController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
